In [22]:
import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import minmax_scale,StandardScaler
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.impute import SimpleImputer,KNNImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

# Part 1 : Data Leakge 
## Case 1 : Leakage via missing value 
If we have missing values in data and we tried to fill  it on entire dataset before filling it , then we have filled the missing values  with average of test data as well .

In [ ]:
df_missing = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Score': [40, 60, np.nan, 80, np.nan, 90]  # Missing scores for C and E
})
print("Original data : ")
display(df_missing)
# first split data into testdata and train data
df_train,df_test=train_test_split(df_missing,test_size=0.2,random_state=42)
print("Training datset")
print()
display(df_train)
print("Testign data : ")
display(df_test)

Original data :

  Student  Score
0       A   40.0
1       B   60.0
2       C    NaN
3       D   80.0
4       E    NaN
5       F   90.0

Training datset

  Student  Score
0       A   40.0
2       C    NaN
4       E    NaN
5       F   90.0

Testign data :

  Student  Score
1       B   60.0
3       D   80.0

In [25]:
#  NOw take the average from training data and fill those values in both of the splited data
imputer=SimpleImputer(strategy="mean")
imputer.fit(df_train[["Score"]])
df_train["Score"]=imputer.transform(df_train[["Score"]])
df_test["Score"]=imputer.transform(df_test[["Score"]])
print("Filled test data : ")
display(df_test)
print("Filled trained data : ")
display(df_train)

Filled test data :

  Student  Score
1       B   60.0
3       D   80.0

Filled trained data :

  Student  Score
0       A   40.0
2       C   65.0
4       E   65.0
5       F   90.0