If a CEO's salary is missing, filling it with the company "average" is wrong. KNN Imputer looks at the K most similar rows (Neighbors) and averages their values.

In [10]:
from sklearn.impute import KNNImputer
import pandas as pd
import numpy as np
# Dummy data: Young vs Older employees
df_employees = pd.DataFrame({
    'Age': [22, 23, 24, 45, 47, 46],
    'Experience': [1, 1, 2, 20, 22, 21],
    'Salary': [30000, 32000, np.nan, 150000, 160000, np.nan]
})
df_employees

   Age  Experience    Salary
0   22           1   30000.0
1   23           1   32000.0
2   24           2       NaN
3   45          20  150000.0
4   47          22  160000.0
5   46          21       NaN

In [16]:
#Training the imputing model
imputer=KNNImputer(n_neighbors=2)
data=imputer.fit_transform(df_employees)
#Filling the values
df_filled=pd.DataFrame(data,columns=df_employees.columns)
display(df_employees)
print(">"*60)
print("The filled dataset : ")
df_filled

   Age  Experience    Salary
0   22           1   30000.0
1   23           1   32000.0
2   24           2       NaN
3   45          20  150000.0
4   47          22  160000.0
5   46          21       NaN

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
The filled dataset :

    Age  Experience    Salary
0  22.0         1.0   30000.0
1  23.0         1.0   32000.0
2  24.0         2.0   31000.0
3  45.0        20.0  150000.0
4  47.0        22.0  160000.0
5  46.0        21.0  155000.0